# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kmeans.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckmeans.proto\x12\x06kmeans\"o\n\rMapperRequest\x12\x11\n\tmapper_id\x18\x01 \x01(\x05\x12#\n\tcentroids\x18\x02 \x03(\x0b\x32\x10.kmeans.Centroid\x12\x13\n\x0brange_start\x18\x03 \x01(\x05\x12\x11\n\trange_end\x18\x04 \x01(\x05\"3\n\x0eMapperResponse\x12\x11\n\tmapper_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\"$\n\x0eReducerRequest\x12\x12\n\nreducer_id\x18\x01 \x01(\x05\"^\n\x0fReducerResponse\x12\x12\n\nreducer_id\x18\x01 \x01(\x05\x12\'\n\rnew_centroids\x18\x02 \x03(\x0b\x32\x10.kmeans.Centroid\x12\x0e\n\x06status\x18\x03 \x01(\t\"\"\n\x0f\x41\x63knowledgement\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x08\x43\x65ntroid\x12\x13\n\x0b\x63oordinates\x18\x01 \x03(\x01\x32\xe9\x01\n\rKMeansCluster\x12\x41\n\x10SendDataToMapper\x12\x15.kmeans.MapperRequest\x1a\x16.kmeans.MapperResponse\x12K\n\x17ReceiveUpdatedCentroids\x12\x17.kmeans.ReducerResponse\x1a\x17.kmeans.Acknowledgement\x12H\n\x15ProcessDataForReducer\x12\x16.kmeans.ReducerRequest\x1a\x17.kmeans.ReducerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kmeans_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPPERREQUEST']._serialized_start=24
  _globals['_MAPPERREQUEST']._serialized_end=135
  _globals['_MAPPERRESPONSE']._serialized_start=137
  _globals['_MAPPERRESPONSE']._serialized_end=188
  _globals['_REDUCERREQUEST']._serialized_start=190
  _globals['_REDUCERREQUEST']._serialized_end=226
  _globals['_REDUCERRESPONSE']._serialized_start=228
  _globals['_REDUCERRESPONSE']._serialized_end=322
  _globals['_ACKNOWLEDGEMENT']._serialized_start=324
  _globals['_ACKNOWLEDGEMENT']._serialized_end=358
  _globals['_CENTROID']._serialized_start=360
  _globals['_CENTROID']._serialized_end=391
  _globals['_KMEANSCLUSTER']._serialized_start=394
  _globals['_KMEANSCLUSTER']._serialized_end=627
# @@protoc_insertion_point(module_scope)
